name: "multi event pipe line"

on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "running in master push"
    on-pull-request:   # job name
        runs-on: ubuntu-latest
        steps:
            - name: "running in pull request"
              run: echo "Running on pull request"